### ISSUE TITLE
Provide Feedback on PRs to Catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#38]
@jag3773 commented on [Mon Jul 17 2017](https://github.com/unfoldingWord-dev/door43.org/issues/631)

## Story

As a *publisher* I want to know that the content I'm trying to publish is valid so that I don't push bad data into the catalog.

## Notes

It would be great if we could allow PRs against the Door43-Catalog to get feedback on the validity of what is trying to be added to the catalog.  The following types of things would need to be reported:

* [ ] Valid USFM
* [ ] Valid manifest file

**Comment by neutrinog** [comment]
are you thinking custom integration like travis or reviewable?

**Comment by jag3773** [comment]
That would be great, but I'm not looking to work on this now @neutrinog .

**Comment by jag3773** [comment]
Validation is being handled directly in DCS now and publishing is handled by catalog next functionality.
