### ISSUE TITLE
Convert USFM3 to USFM2 For Backwards Compatibilty

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#39]
@jag3773 commented on [Fri Aug 11 2017](https://github.com/unfoldingWord-dev/door43.org/issues/668)

For resources in our catalog that move to use USFM 3 we want to add a converter into the API pipeline that will convert them to USFM2 and add that as another format in the API.  Intended result is 2 entries in the formats array, one for the original USFM3 version and one for the stripped down USFM2 version.

The operation should be triggered by the `formats` key in the manifest being set to `text/usfm3`.  In our ecosystem `text/usfm` equates to USFM2.

In addition, the USFM2 text can be used for the tS/uW backwards compatibility generators.

**Comment by neutrinog** [comment]
@jag3773  I think now's the time to start looking into using a queue for processing things in the api.
I don't have a good spot to put all of this processing without slowing down and possibly breaking things.
I think we need to adjust the webhook to submit requests to a queue and then have a worker process items in the queue.

This is what I propose:
* webhook - large rewrite
* signing - small rewrite
* catalog - small rewrite
* service worker - new function

we could limp along with what we have by placing this processing in the webhook, but we're at a crossroads or close to it. We're bound to add more data intensive processing and I'm concerned about timeouts.

**Comment by neutrinog** [comment]
On the bright side this is the best place in the api to begin implementing a queue pattern. I won't have to touch the tS or uW api code.

**Comment by neutrinog** [comment]
Let's think about creating a new lambda that will be triggered when the webhook uploads something. This lambda will generate the usfm2 and upload it. The webhook will inject the usfm2 links into the catalog record.
The signing and publishing will just fail and restart until this new lambda generates the usfm2 files.

**Comment by neutrinog** [comment]
Just noting that the usfm3 to usfm2 converter is completed with tests. I've removed any changes made to the existing lambda.

I'll wait to begin constructing a new lambda until we have our meeting regarding the improvements to the api.

**Comment by jag3773** [comment]
Yes, that sounds fine @neutrinog and @ethantkoenig .

**Comment by neutrinog** [comment]
Here is some code that converts USFM3 to USFM2. At this point I don't think it covers all the new features in usfm3 but it's a starting point. https://github.com/unfoldingWord-dev/d43-catalog/blob/develop/libraries/tools/usfm_utils.py#L338
