### ISSUE TITLE
tN Link Expansion Issue

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#41]
For some reason there are *some* links in tN that are getting a link name injected in the tS API conversion process.  For example, there is a [tN for Acts 17:1](https://git.door43.org/Door43/en_tn/src/master/act/17/01.md) that links to `[[rc://en/ta/man/translate/translate-names]]`.  However, in the [tS API endpoint](https://api.unfoldingword.org/ts/txt/2/act/en/notes.json?date_modified=20170221) (item 255.tn.4) it shows up as `[[:en:ta:vol1:translate:translate_names|How to Translate Names]]`.

There are other seemingly random occurrences of this phenomena as well.

In contrast, [Acts 1:1](https://git.door43.org/Door43/en_tn/raw/master/act/01/01.md) also has a link to translate_names but it does not get the link name injected.

tS Desktop 11.1 is not able to handle the links that have the link names injected, so it is preferable to not inject any link names into the tS v2 API endpoint.

**Comment by neutrinog** [comment]
@jag3773 actually `[[:en:ta:vol1:translate:translate_names|How to Translate Names]]` is the proper form. That has been the preferred for since before tS desktop.

**Comment by neutrinog** [comment]
I am however investigating how the links are generated and am having trouble figuring out how the titles are getting there in the first place!

**Comment by neutrinog** [comment]
@jag3773 tS Desktop does not show the title in Acts 1:1 because the indexed data is a bit outdated and is missing the title in the link.

**Comment by neutrinog** [comment]
It was determined there was no inconsistency.
The tS api is displaying all the links without titles. tS android is automatically displaying titles by reading the cached data. tS desktop is simply displaying the slug.
