### ISSUE TITLE
Freeze tw_cat in tS v2 catalog

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#42]
We are removing the list of tWs that are maintained in the tN but we want the existing list to stay as-is for translationStudio.

The `tw_cat.json` files for each resource-language should be frozen, so that future updates don't overwrite them.

**Comment by neutrinog** [comment]
this is finished. Though we still need to complete #44 before we can begin pushing the updated tN into the catalog.
