### ISSUE TITLE
Resources Endpoint

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#45]
## Story

As a _developer_, I want to be able to get a list of content for a particular resource instead of having to read the entire `catalog.json`.

As a _user_, I don't want to wait a long time for the https://openbiblestories.squarespace.com/library/ page to load.

## Notes

The d43-catalog needs to start outputting a JSON file that only lists the resources that are in the `catalog.json` endpoint by `identifier`.

This process should happen whenever the main `catalog.json` file is updated.

The format of the JSON files should be the same as the `catalog.json`, excepting the `catalogs` array.  Hence, only `languages` should be seen as a top level array in the output files.

## Acceptance Criteria

* This should be a lambda function that is triggered via S3 anytime the catalog.json file is updated
* Every unique resource in `catalog.json` has a corresponding endpoint at /v3/resources/{identifier}.json, for example:
  * A list of OBS resources are found at /v3/resources/obs.json
  * A list of tN resources are found at /v3/resources/tn.json
  * A list of tA resources are found at /v3/resources/ta.json
  * A list of BLV resources are found at /v3/resources/blv.json
* Documentation is updated at http://api-info.readthedocs.io/en/latest/door43.html .

**Comment by jag3773** [comment]
In particular, you mean removing the spaces, right @phillip-hopper (line breaks are not present in the current version)?

**Comment by phillip-hopper** [comment]
Yes, @jag3773. I actually just ran it through https://www.cleancss.com/json-minify/.

**Comment by jag3773** [comment]
This issue was solved in a slightly different manner in #52.
