### ISSUE TITLE
Media for YLB Not Included

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#54]
The Yaleba OBS has been published in the catalog but it doesn't look like any of the media has been added to the catalog.  Project is at https://git.door43.org/Door43-Catalog/ylb_obs .

One unique feature here is that there is no text of this project, it is only audio and video.

**Comment by neutrinog** [comment]
Made some fixes in the api and also a content fix here https://git.door43.org/STR/ylb_obs/pulls/1

**Comment by jag3773** [comment]
This is now fixed, thanks @neutrinog
