### ISSUE TITLE
tS v2 Catalog Not Receiving tW

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#55]
We have published tW resources in several languages recently but the resources are not being converted properly into the tS API and hence they are not available in the tool.

For example, Hindi tW is in the catalog, https://git.door43.org/Door43-Catalog/hi_tw, but the terms do not show up in the tS v2 resources endpoint (e.g. https://api.unfoldingword.org/ts/txt/2/tit/hi/resources.json ).

See [this doc](https://docs.google.com/document/d/1DkKfHSGNjos0EDg0Ek514KXEDAoqKhObTjV_QN776VE/) for steps to reproduce in tS.

It's possible that this is related to https://github.com/unfoldingWord-dev/d43-catalog/issues/42 .  If that is the case, we need to come up with a way of copying this information over for other languages.  Is it a matter of needing a [config.yaml](https://git.door43.org/Door43-Catalog/en_tw/src/branch/master/bible/config.yaml) file in each tW project?

**Comment by neutrinog** [comment]
> **Todd Price**: We have translated and published translationWords in Croatian (hrvatski jezik). But whenever I try to begin a new project translating from Croatian, the 'Words' tab still gives me the English, not the Croatian.

**Comment by neutrinog** [comment]
Also note that the IRV and UDB are not added as resources. only the ULB is added.

**Comment by neutrinog** [comment]
the ts api needs to support formats that are `text/usfm3`

**Comment by neutrinog** [comment]
I think this is fixed now. Need to wait for the api to rebuild.

**Comment by neutrinog** [comment]
Just checked the API and I think this is still broken. 🙁

**Comment by neutrinog** [comment]
ok I just realized the api is now working correctly. The link to the resources above is not correct. 
Here's the actual link https://cdn.door43.org/v2/ts/tit/hi/resources.json?date_modified=20190424

**Comment by jag3773** [comment]
@neutrinog While I can see things are working for Hindi, there are several other languages that don't appear to be working.  Here is a list (compliments of @russp41 ):

| GL | tS tW language |
|----|-----------------|
| Nepali    |   Nepali |
| Hindi       |  Hindi |
| Bengali   |   English |
| Gujarati   |  English |
| Punjabi   |   English |
| Oriya      |    English |
| Assamese |  English |
| Marathi   | ULB/IRV not showing in source list |
| Kannada  |   Kannada |
| Tamil        |   English |
| Telugu      |   English |
| Malayalam | English |
| Urdu-Deva  English |

For example looks like https://cdn.door43.org/v2/ts/tit/bn/resources.json references `bn` translation words (https://cdn.door43.org/v2/ts/bible/bn/words.json) but those don't seem to be getting into the app for some reason.

**Comment by neutrinog** [comment]
I double checked everything and it's actually working fine. I just forgot that the updated content needs to replace the old content when they install the updated version of tS.

**Comment by neutrinog** [comment]
ok I made a really tiny fix and now all of those work except for a few exceptions.

* Marathi is mostly completely broken. I can't get it to display at all. So I'll need to inspect the content.
* Urdu-Deva does not have any translated helps. See https://cdn.door43.org/v2/ts/tit/ur-Deva/resources.json

**Comment by neutrinog** [comment]
We believe the above two repos have been fixed. This can be confirmed after the ts api has finished re-building.
