### ISSUE TITLE
UST Missing Words

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord-dev/d43-catalog#58]
The UST text in https://cdn.door43.org/v2/ts/tit/en/ust/v4/source.json?date_modified=20190626 is missing words, probably related to https://github.com/unfoldingWord-dev/ts-desktop/issues/1256 .

**Comment by jag3773** [comment]
Same problem with the ULT it appears.

**Comment by neutrinog** [comment]
Both have the words.
This must be a bug in the apps.

![image](https://user-images.githubusercontent.com/166412/61087750-65149300-a3eb-11e9-8691-a8706735ab9f.png)

**Comment by neutrinog** [comment]
oh, sorry I thought you meant translationWords.
Yes, I was wondering why the ULT and UST text looked wonky.

**Comment by neutrinog** [comment]
ok I discovered the issue. This has been fixed.
